[template] README.md correction for ANDROID mobile installation
ocsigen/ocsigen-start pull request #626
Opened 2021-05-05 10:04 UTC by RodiBozman

Since the tutorial about the android installation did not work very well, here is the new version of the README for the template.

2021-05-05 10:09 UTC, jrochel requested changes

2021-05-05 10:09 UTC, jrochel commented on template.distillery/README.md
> -** Be prepared! You're entering an unstable world! **
Je laisserais ce commentaire.

2021-05-05 10:09 UTC, jrochel commented on template.distillery/README.md
> +If npm is causing a lot of errors in the following parts of the installation a crucial advice would be to uninstall nodejs and npm and do a clean installation of them **with aptitude**.
Ça s'applique uniquement à Debian. Ni apt-get ni aptitude existent dans des autres distributions de Linux.

2021-05-05 10:11 UTC, RodiBozman commented on template.distillery/README.md
> -** Be prepared! You're entering an unstable world! **
Le commentaire existe toujours, il a juste été modifié car il y avait une typo regarde bien, la personne précédente a voulu mettre en gras la phrase mais a mis des espaces des 2 côté de la phrase.

2021-05-05 10:12 UTC, jrochel commented on template.distillery/README.md
> -** Be prepared! You're entering an unstable world! **
Effectivement.

2021-05-05 10:14 UTC, RodiBozman commented on template.distillery/README.md
> +If npm is causing a lot of errors in the following parts of the installation a crucial advice would be to uninstall nodejs and npm and do a clean installation of them **with aptitude**.
C'est corrigé.

2021-05-07 15:20 UTC, balat commented on template.distillery/README.md
> +If this part of the installation is bringing a lot of errors you may want to try the version 2.0 for the Android installation. You can find it down below.
Remove this?

2021-05-10 07:35 UTC, RodiBozman commented on template.distillery/README.md
> +If this part of the installation is bringing a lot of errors you may want to try the version 2.0 for the Android installation. You can find it down below.
Done

2021-05-10 12:55 UTC, merged